apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  labels:
    app: demo-app
  annotations:
    argocd-image-updater.argoproj.io/image-list: demo-app=docker.io/syash7202/demo-app
    argocd-image-updater.argoproj.io/demo-app.update-strategy: latest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: syash7202/demo-app:v20250825082937
          ports:
            - containerPort: 5000